name: Nifty Option Chain Update

on:
  schedule:
    - cron: "*/1 3-9 * * 1-5"  
    - cron: "0 10 * * 1-5"
jobs:
  run:
    runs-on: ubuntu-latest
    concurrency:
      group: nifty-live-update
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt --no-cache-dir

      - name: Install Playwright browser
        run: |
          playwright install chromium

      - name: Save Google credentials
        run: |
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' > service_account.json
          test -s service_account.json || exit 1

      - name: Run script
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
          GOOGLE_CREDENTIALS_PATH: ${{ github.workspace }}/service_account.json
        run: python NSE_Option_Chainonline.py

      - name: Upload logs (for debugging)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: nifty-logs
          path: option_chain.log
